<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Código</th>
            <th>Banco</th>
            <th>Agência</th>
            <th>Conjunta</th>
            <th>Nome conjunta</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->contasCorrente as $cc): ?>
            <tr>
                <td><?= $this->escapeHtml($cc->getId()); ?></td>
                <td><?= $this->escapeHtml($cc->getSequencia()); ?></td>
                <td><?= $this->escapeHtml($cc->getBanco()->getBanco()); ?></td>
                <td><?= $this->escapeHtml($cc->getAgencia()); ?></td>
                <td><?= $this->escapeHtml($cc->getConjunta()); ?></td>
                <td><?= $this->escapeHtml($cc->getNomeConjunta()); ?></td>

                <td><button type="button" class="btn btn-primary btn-sm pull-center"
                            onclick="editarContaCorrente('<?php echo $cc->getId();?>')"
                       href="<?= $this->url('sig-rh/conta-corrente', ['action' => 'save', 'id' => $cc->getId()]) ?>"
                       title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></button>
                    <a class="btn btn-primary btn-sm pull-center"
                       href="<?= $this->url('sig-rh/conta-corrente', ['action' => 'delete', 'id' => $cc->getId()]) ?>"
                       title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
