<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Banco</th>
            <th>Agência</th>
            <th>Conta corrente</th>
            <th>Conjunta</th>
            <th>Nome conjunta</th>
            <th>Cpf conjunta</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        $user = $this->identity();
        foreach ($this->contasCorrente as $cc): ?>
            <tr>
                <td><?php echo $this->escapeHtml($cc->getBanco()->getBanco()); ?></td>
                <td><?php echo $this->escapeHtml($cc->getAgencia()); ?></td>
                <td><?php echo $this->escapeHtml($cc->getContaCorrente()); ?></td>
                <td><?php echo ($cc->getConjunta() ? "Sim":"Não"); ?></td>
                <td><?php echo $this->escapeHtml($cc->getNomeConjunta()); ?></td>
                <td><?php echo $this->escapeHtml($cc->getCpfConjunta()); ?></td>

                <td><?php if($user['papel'] != 3):?>
                    <button type="button" class="btn btn-primary btn-sm pull-center"
                            onclick="editarContaCorrente('<?php echo $cc->getId();?>')"
                       title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></button>
                    <button type="button" class="btn btn-primary btn-sm pull-center" 
                               onclick="excluirContaCorrente('<?php echo $cc->getId();?>')"
                        title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></button>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
