<?= $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-md-12">
        <h3 class="panel-title">
            Por favor, preencha o formulário abaixo e, em seguida, clique sobre
            o botão <i>Salvar</i>. 
        </h3>
        <div class="row">
            <div class="col-md-6">

                <?php echo $this->formLabel($this->form->get('banco')); ?><br>
                <?php echo $this->formElement($this->form->get('banco')); ?>
                <?php echo $this->formElementErrors($this->form->get('banco')); ?>                  
            </div>

            <div class="col-md-3">
                <?= $this->formLabel($this->form->get('agencia')); ?><br>
                <?= $this->formElement($this->form->get('agencia')); ?>
                <?= $this->formElementErrors($this->form->get('agencia')); ?>                  
            </div>

            <div class="col-md-3">
                <?= $this->formLabel($this->form->get('contaCorrente')); ?><br>
                <?= $this->formElement($this->form->get('contaCorrente')); ?>
                <?= $this->formElementErrors($this->form->get('contaCorrente')); ?>                  
            </div>    
        </div>
        <div class="row">
            <div class="col-md-2">
                <?= $this->formLabel($this->form->get('conjunta')); ?><br>
                <?= $this->formElement($this->form->get('conjunta')); ?>
                <?= $this->formElementErrors($this->form->get('conjunta')); ?>                  
            </div>

            <div class="col-md-7">
                <?= $this->formLabel($this->form->get('nomeConjunta')); ?><br>
                <?= $this->formElement($this->form->get('nomeConjunta')); ?>
                <?= $this->formElementErrors($this->form->get('nomeConjunta')); ?>                  
            </div>
            <div class="col-md-3">
                <?= $this->formLabel($this->form->get('cpfConjunta')); ?><br>
                <?= $this->formElement($this->form->get('cpfConjunta')); ?>
                <?= $this->formElementErrors($this->form->get('cpfConjunta')); ?>                  
            </div>

        </div>
    </div>
</div>
</div>
<?= $this->form()->closeTag(); ?>