<?php
$form = $this->form;
$form->get('descricao')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite a descrição aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de bancos</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Editar</i>.
                </h3>
            </div>

            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                <?= $this->formLabel($form->get('descricao')); ?><br>
                <?= $this->formElement($form->get('descricao')); ?>
                <?= $this->formElementErrors($form->get('descricao')); ?>                  
                <br><br>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>

</div>
