<script src="/js/inputmask.js"></script>
<script src="/js/jquery.inputmask.js"></script>

<h1>Registro de ponto</h1>
<form method="get" action="/sig-rh/movimentacao-ponto/index">
    <div class="row">
        <div class="col-md-2">
            <label for="matricula">Matrícula</label>
            <input class="form-control" type="text" name="matricula" id="matricula" value="<?php echo (null != $this->colaborador) ? $this->colaborador->getMatricula() : ''; ?>">
        </div>
        <div class="col-md-2">
            <label for="referencia">Período (mês/ano)</label>
            <input pattern="(0[1-9]|1[012]).[0-9]{4}" title="Referência (mm/aaaa)" class="form-control" type="text" name="referencia" id="referencia" value="<?php echo (null != $this->referencia) ? $this->referencia : ''; ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" class="btn btn-sm" value="Enviar">
        </div>
    </div>

<?php

if ($this->folhaPonto != null):    
    $diasSemana = [0 => "Domingo", 1 => "Segunda-feira", 2 => "Terça-feira", 3 => "Quarta-feira", 4 => "Quinta-feira", 5 => "Sexta-feira", 6 => "Sábado"];
    $movimentacoesPonto = $this->folhaPonto->getMovimentacaoPonto();
    $referencia = $this->folhaPonto->getReferencia();
?>
    <hr>
    <h3><a href="/sig-rh/colaborador/save/<?php echo $this->colaborador->getMatricula(); ?>">
            <?php echo $this->escapeHtml($this->colaborador->getNome()); ?></a>
    </h3>
    <hr>
    
    <div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Data</th>
                <th>Dia da semana</th>
                <th>Hora do registro</th>
                <th>Total de horas no dia</th>
                <th>Observações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($movimentacoesPonto as $movimentacaoPonto):
                $dataPonto = \DateTime::createFromFormat("Ymd", $referencia.$movimentacaoPonto->getDiaPonto());
                if( ($dataPonto->format('w') == 0) || ($dataPonto->format('w') == 6) ) {?>
                    <tr style="background-color: #F0FFFF;">
                    <?php } else {?>
                        <tr>
                    <?php }?>
                <td><?php echo $this->escapeHtml($dataPonto->format("d/m/Y"));?></td>
                <td><?php echo $this->escapeHtml($diasSemana[$dataPonto->format("w")]); ?></td>
                <td><?php foreach($movimentacaoPonto->getRegistros() as $registro):
                    echo $this->escapeHtml($registro->getHoraRegistro()->format("H:i"). " ");
                    endforeach;?>
                    
                </td>
                <td></td>
                <td></td>
            </tr>
            <?php endforeach;?>

        </tbody>
        </table>
    </div>
<?php endif; ?>
</form>


<script>
    $("#matricula").inputmask("999999");
    $("#periodoMovimentacao").inputmask("99/9999");
</script>
