<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('id'));

?>
<div class="row titulo">
<div class="col-sm-8" >
    <h3>Usuário <small>-> Cadastro</small></h3>
</div>
</div>

<div class="row">
    <div class="col-sm-4">
        <?php
        echo $this->formLabel($form->get('nome'));
        echo $this->formInput($form->get('nome'));
        ?>
    </div>

   <div class="col-sm-3">
        <?php
        echo $this->formLabel($form->get('login'));
        echo $this->formInput($form->get('login'));
        ?>
    </div>

   <div class="col-sm-4">
        <?php
        echo $this->formLabel($form->get('funcao'));
        echo $this->formSelect($form->get('funcao'));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <?php
        echo $this->formLabel($form->get('email'));
        echo $this->formInput($form->get('email'));
        ?>
    </div>

   <div class="col-sm-2">
        <?php
        echo $this->formLabel($form->get('ramal'));
        echo $this->formInput($form->get('ramal'));
        ?>
    </div>

   <div class="col-sm-2">
        <?php
        echo $this->formLabel($form->get('usaldap'));
        echo $this->formInput($form->get('usaldap'));
        ?>
    </div>
    
   <div class="col-sm-3">
        <?php
        echo $this->formLabel($form->get('senha'));
        echo $this->formInput($form->get('senha'));
        ?>
    </div>
    
   <div class="col-sm-3">
        <?php
        echo $this->formLabel($form->get('matricula'));
        echo $this->formSelect($form->get('matricula'));
        ?>
    </div>
    
    
</div>

<div class="row" style="margin-top: 20px">
    <div class="col-sm-12" >
<?php echo $this->formInput($form->get('submit')); ?> 
    </div>
</div>
<?php echo $this->formElementErrors($form);
echo $this->form()->closeTag();
?>