<?php
    $title = 'Excluir um registro';
    $url   = $this->url('sig-rh/dependente', ['action' => 'delete-modal', 'id' => $dependente->getId()]);
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
    "<?php echo $this->escapeHtml($dependente->getNome()); ?>"
</p>

<form action="<?php echo $url; ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?php echo (int) $dependente->getId(); ?>" />
    </div>
</form>