<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Grau de parentesco</th>
            <th>Data de Nascimento</th>
            <th>Ativo</th>
            <th>Universitário</th>
            <th>Salário Família</th>
            <th>Imposto de Renda</th>
        </tr>
    </thead>
    <tbody>
        <?php 
        $user = $this->identity();
        foreach ($this->dependentes as $dependente): ?>
            <tr>
                <td><?php echo $this->escapeHtml($dependente->getNome()); ?></td>
                <td><?php echo $this->escapeHtml($this->grauParentesco[$dependente->getGrauParentesco()]); ?></td>
                <td><?php echo $this->escapeHtml(null!= $dependente->getDataNascimento()?$dependente->getDataNascimento()->format("d/m/Y"):''); ?></td>
                <td><?php echo $dependente->getAtivo() ? "Sim" : "Nao"; ?></td>
                <td><?php echo $dependente->getUniversitario() ? "Sim": "Não"; ?></td>
                <td><?php echo $dependente->getSalarioFamilia() ? "Sim":"Não"; ?></td>
                <td><?php echo $dependente->getImpostoRenda() ? "Sim":"Não"; ?></td>

                <td>
                    <?php if($user['papel'] != 3):?>
                        <button type="button" class="btn btn-primary btn-sm pull-center"
                                onclick="editarDependente('<?php echo $dependente->getId();?>')"
                                title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></button>
                        <button type="button" class="btn btn-primary btn-sm pull-center" 
                                onclick="excluirDependente('<?php echo $dependente->getId();?>')"
                                title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></button>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>
