<h1>Dependentes cadastrados</h1>
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Grau de parentesco</th>
                <th>Data de Nascimento</th>
                <th>Ativo</th>
                <th>Universitário</th>
                <th>Salário Família</th>
                <th>Imposto de Renda</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->dependentes as $dependente): ?>
                <tr>
                    <td><?= $this->escapeHtml($dependente->getNome()); ?></td>
                    <td><?= $this->escapeHtml($dependente->getGrauParentesco()); ?></td>
                    <td><?= $this->escapeHtml($dependente->getDataNascimento()); ?></td>
                    <td><?= $this->escapeHtml($dependente->getAtivo()); ?></td>
                    <td><?= $this->escapeHtml($dependente->getUniversitario()); ?></td>
                    <td><?php echo $this->escapeHtml($dependente->getSalarioFamilia()); ?></td>
                    <td><?php echo $this->escapeHtml($dependente->getImpostoRenda()); ?></td>
                    
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/dependente', ['action' => 'save', 'id' => $dependente->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/dependente', ['action' => 'delete', 'id' => $dependente->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?= $this->paginationControl($this->dependentes, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/dependente']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/dependente/save">Novo
        registro</a>
</div>
