<h1>Instituições cadastradas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Razão social</th>
                <th>Nome fantasia</th>
                <th>PF/PJ</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->instituicoes as $instituicao): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($instituicao->getCodInstituicao()); ?></td>
                    <td><?php echo $this->escapeHtml($instituicao->getDesRazaoSocial()); ?></td>
                    <td><?php echo $this->escapeHtml($instituicao->getNomFantasia()); ?></td>
                    <td><?php echo $this->escapeHtml($instituicao->getDesPfPj()); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/instituicao', ['action' => 'save', 'id' => $instituicao->getCodInstituicao()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->instituicoes, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/instituicao']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/instituicao/save">Novo registro</a>
</div>
