<?php
    $this->headScript()->appendFile('/js/inputmask.js', 'text/javascript');
    $this->headScript()->appendFile('/js/jquery.inputmask.js', 'text/javascript');


$form = $this->form;

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de instituições</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/instituicao" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('desRazaoSocial')); ?><br>
                        <?php echo $this->formElement($form->get('desRazaoSocial')); ?>
                        <?php echo $this->formElementErrors($form->get('desRazaoSocial')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('nomFantasia')); ?><br>
                        <?php echo $this->formElement($form->get('nomFantasia')); ?>
                        <?php echo $this->formElementErrors($form->get('nomFantasia')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cnpj')); ?><br>
                        <?php echo $this->formElement($form->get('cnpj')); ?>
                        <?php echo $this->formElementErrors($form->get('cnpj')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('inscricaoEstadual')); ?><br>
                        <?php echo $this->formElement($form->get('inscricaoEstadual')); ?>
                        <?php echo $this->formElementErrors($form->get('inscricaoEstadual')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('endereco')); ?><br>
                        <?php echo $this->formElement($form->get('endereco')); ?>
                        <?php echo $this->formElementErrors($form->get('endereco')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('bairro')); ?><br>
                        <?php echo $this->formElement($form->get('bairro')); ?>
                        <?php echo $this->formElementErrors($form->get('bairro')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('cep')); ?><br>
                        <?php echo $this->formElement($form->get('cep')); ?>
                        <?php echo $this->formElementErrors($form->get('cep')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('caixaPostal')); ?><br>
                        <?php echo $this->formElement($form->get('caixaPostal')); ?>
                        <?php echo $this->formElementErrors($form->get('caixaPostal')); ?>                  
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('cidade')); ?><br>
                        <?php echo $this->formElement($form->get('cidade')); ?>
                        <?php echo $this->formElementErrors($form->get('cidade')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('uf')); ?><br>
                        <?php echo $this->formElement($form->get('uf')); ?>
                        <?php echo $this->formElementErrors($form->get('uf')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('pais')); ?><br>
                        <?php echo $this->formElement($form->get('pais')); ?>
                        <?php echo $this->formElementErrors($form->get('pais')); ?>                  
                    </div>
                    <div class="col-md-2">
                        <?php echo $this->formLabel($form->get('telefone')); ?><br>
                        <?php echo $this->formElement($form->get('telefone')); ?>
                        <?php echo $this->formElementErrors($form->get('telefone')); ?>                  
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('email')); ?><br>
                        <?php echo $this->formElement($form->get('email')); ?>
                        <?php echo $this->formElementErrors($form->get('email')); ?>                  
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formLabel($form->get('homepage')); ?><br>
                        <?php echo $this->formElement($form->get('homepage')); ?>
                        <?php echo $this->formElementErrors($form->get('homepage')); ?>                  
                    </div>
                </div>
                
                <br>
                <div class="row">
                    <?php echo $this->formElement($form->get('submit')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#cnpj").inputmask("99.999.999/9999-99");
    $("#cep").inputmask("99999-999");
    $("#telefone").inputmask("(99) 99999-9999");
    
    $("#telefone").focusin(function() {
        $(this).inputmask('(99) 99999-9999');
    });   
    
    $("#telefone").focusout(function() {
        $(this).val().replace(/\D/g,'').length === 11 ? $(this).inputmask('(99) 99999-9999') : $(this).inputmask('(99) 9999-9999');
    });

</script>    