<h1>Importações realizadas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Referência</th>
                <th>Data da importação</th>
                <th>Usuário</th>
                <th>Log</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->importacoesPonto as $importacao): ?>
                <tr>
                    <td><?php echo $this->escapeHtml(substr($importacao->getReferencia(), 4,2)."/".substr($importacao->getReferencia(), 0,4)); ?></td>
                    <td><?php echo $this->escapeHtml($importacao->getDataImportacao()->format("d/m/Y")); ?></td>
                    <td><?php echo $this->escapeHtml($importacao->getUsuario()->getNome()); ?></td>
                    <td><?php echo $this->escapeHtml(substr($importacao->getLog(), 0, 80)." ..."); ?></td>
                    <td></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->importacoesPonto, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/importacao-ponto']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/importacao-ponto/save">Nova importação</a>
</div>
