<?php
$this->headScript()->appendFile('/js/importacao-ponto-save.js', 'text/javascript');
$form = $this->form;
$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Imporação do registro das catracas</h1>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/importacao-ponto?page=<?php echo $this->page;?>" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php $this->form->prepare(); ?>
                
                <?php echo $this->form()->openTag($form); ?>
                <?php echo $this->formRow($form->get('dataServidor')); ?>

                <div class="form-group row">
                        <div class="col-md-4"><?php echo $this->formRow($form->get('referencia')); ?></div>
                        <div class="col-md-4"><?php echo $this->formRow($form->get('dataImportacao')); ?></div>
                        <div class="col-md-4"><?php echo $this->formRow($form->get('usuario')); ?></div>
                </div>
                
                <div class="form-group row">
                        <div class="col-md-12"><?php echo $this->formRow($form->get('arquivo')); ?></div>
                </div>
                
                <hr>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
