<?php echo $this->doctype(); ?>
 
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css','screen,print')
                ->prependStylesheet($this->basePath() . '/css/style.css','screen,print') //especificar que eh pra impressão tb
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css','screen,print')
        ?>
    </head>
    <body>
        <!--div style="width:900px;margin-left: auto;margin-right: auto;"-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <img src="/images/cnpso.png" >
                </div>
                <div class="col-sm-8">
                    <h2><?php echo $this->titulo_impressao ?></h2>
                </div>
            </div>
            
            
            
        <?php
        echo $this->content;
        ?>
        </div>
    </body>


</html>