<?php echo $this->doctype(); ?>
 
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />        
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css','print')
                ->prependStylesheet($this->basePath() . '/css/style.css','screen, print') //especificar que eh pra impressão tb
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css','screen,print')
        ?>
    </head>
    <body>
        <!--div style="width:900px;margin-left: auto;margin-right: auto;"-->
        <div class="container">
            <?php echo $this->content;?>
        </div>
    </body>


</html>