<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema de Gestão de Recursos Humanos da Embrapa Soja (SigRH)')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/embrapa.png') ?>" height="28" alt="SigRH"/>
                 </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Início</a></li>
                        
                        <?php if ($this->identity() != null):?>
                        
                        <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Cadastros<span class="caret"></span></a>
                        	<ul class="dropdown-menu">
                                    <li><a href="/sig-rh/banco">Banco</a></li>
                                    <li><a href="/sig-rh/colaborador">Colaborador</a></li>
                                    <li><a href="/sig-rh/cor-pele">Cor de pele</a></li>
                                    <li><a href="/sig-rh/curso">Curso</a></li>
                                    <li><a href="/sig-rh/estado-civil">Estado civil</a></li>
                                    <li><a href="/sig-rh/fonte-seguro">Fonte seguro</a></li>
                                    <li><a href="/sig-rh/grupo-sanguineo">Grupo sanguíneo</a></li>
                                    <li><a href="/sig-rh/linha-onibus">Linha de ônibus</a></li>
                                    <li><a href="/sig-rh/modalidade-bolsa">Modalidade bolsa</a></li>
                                    <li><a href="/sig-rh/nivel">Nível</a></li>
                                    <li><a href="/sig-rh/tipo-colaborador">Tipo de colaboradores</a></li>
                        	</ul>
                        </li>

                        <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Opções<b class="caret"></b></a>
                        <ul class="dropdown-menu">
    	            		<li><a href="/users">Gerenciar usuários</a></li>
    	            		<li><a href="/logout">Sair</a></li>
    	            	</ul>
	                    <?php endif;?>

                        
                        
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> - Empresa Brasileira de Pesquisa Agropecuária - Embrapa Soja.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
