<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema de Gestão de Recursos Humanos da Embrapa Soja (SigRH)')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
//            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.serializeObject.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/embrapa.png') ?>" height="28" alt="SigRH"/>
                 </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Início</a></li>
                        
                        <?php if ($this->identity() != null): 
                            $user = $this->identity(); // pegar o usuario logado da sessao e salvar em uma variavel para verificacoes de papel por exemplo?> 
                        
                            <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Cadastros<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/sig-rh/colaborador/index?nome=&ativo=S&tipoColaborador=2">Colaborador</a></li>
                                        <li><a href="/sig-rh/convenio">Convênio</a></li>
                                    </ul>
                            </li>

                            <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Relatórios<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/sig-rh/rel-colaborador/index">Relatório Colaborador</a></li>
                                    </ul>
                            </li>


                            <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Ponto<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/sig-rh/importacao-ponto">Importar arquivo com movimentação das catracas</a></li>
                                        <li><a href="/sig-rh/folha-ponto">Gerenciar folhas de ponto dos estudantes</a></li>
<!--                                        <li><a href="/sig-rh/ocorrencia/gerar">Gerar ocorrências</a></li>
                                        <li><a href="/sig-rh/batida-ponto/folha-ponto">Gerar folha ponto dos estagiários</a></li>-->
                                        <!--<li><a href="/sig-rh/movimentacao-ponto">Visualizar o registro das catracas por colaborador e período </a></li>-->
                                        <li><a href="/sig-rh/folha-ponto/estudante">Área do estudante</a></li>
                                    </ul>
                            </li>

                            <?php if ( in_array( $user['papel'], array('1','2','3')) ): ?>
                            <li class="dropdown"><a class="dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">Cadastros periféricos<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/sig-rh/agente-integracao">Agente de integração</a></li>
                                        <li><a href="/sig-rh/banco">Banco</a></li>
                                        <li><a href="/sig-rh/cidade">Cidade</a></li>
                                        <li><a href="/sig-rh/cor-pele">Cor de pele</a></li>
                                        <li><a href="/sig-rh/curso">Curso</a></li>
                                        <li><a href="/sig-rh/estado-civil">Estado civil</a></li>
                                        <li><a href="/sig-rh/feriado">Feriado</a></li>
                                        <li><a href="/sig-rh/fonte-seguro">Fonte seguro</a></li>
                                        <li><a href="/sig-rh/grupo-sanguineo">Grupo sanguíneo</a></li>
                                        <li><a href="/sig-rh/instituicao">Instituição</a></li>
                                        <li><a href="/sig-rh/justificativa">Justificativa (ponto)</a></li>
                                        <li><a href="/sig-rh/linha-onibus">Linha de ônibus</a></li>
                                        <li><a href="/sig-rh/modalidade-bolsa">Modalidade bolsa</a></li>
                                        <li><a href="/sig-rh/nivel">Nível</a></li>
                                        <li><a href="/sig-rh/tipo-vinculo">Tipo de vínculo</a></li>
                                    </ul>
                            </li>
                            <?php endif;?>
                            
                            <li><a href="/logout">Sair</a></li>
                        <?php endif;?>
                    </ul>
                    
                </div>
            </div>
        </nav>
        
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> - Empresa Brasileira de Pesquisa Agropecuária - Embrapa Soja.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
