<form method="get" action="/sig-rh/cidade/index">
    <div class="row" style="padding-top: 10px;">
        <div class="col-md-6"></div>
        <div class="col-md-5">
            <input class="form-control" type="text" name="search" placeholder="Digite aqui para pesquisar" id="search" value="<?php echo (null != $this->search) ? $this->search : ''; ?>">
        </div>
        <div class="col-md-1">
            <button class="btn-primary btn-sm" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </div>
    </div>
</form>

<div class="row titulo" >
</div>


<h1>Cidades cadastradas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->cidades as $cidade): ?>
                <tr>
                    <td><?= $this->escapeHtml($cidade->getCidade()); ?></td>
                    <td><?= $this->escapeHtml($cidade->getEstado()->estado); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?= $this->url('sig-rh/cidade', ['action' => 'save', 'id' => $cidade->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <!--a class="btn btn-primary btn-sm pull-center"
                           href="<?php //echo $this->url('sig-rh/cidade', ['action' => 'delete', 'id' => $cidade->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a-->
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?= $this->paginationControl($this->cidades, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/cidade']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/cidade/save">Novo
        registro</a>
</div>
