
<h1>Cadastro de cidades</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/cidade" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>

            <div class="col-sm-12 col-md-4 col-lg-3">
                <?= $this->formLabel($form->get('cidade')); ?><br>
                <?= $this->formElement($form->get('cidade')); ?>
                <?= $this->formElementErrors($form->get('cidade')); ?>                  
            </div>

            <div class="col-sm-12 col-md-4 col-lg-3">
                <?php echo $this->formLabel($form->get('estado')); ?><br>
                <?php echo $this->formElement($form->get('estado')); ?>
                <?php echo $this->formElementErrors($form->get('estado')); ?>                  
            </div>
                
            <div class="row" style="margin-top: 20px">
            <div class="col-sm-12 col-md-4 col-lg-3">
                <br>
                <div class="col-sm-12" >
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
            </div>
                

            <?= $this->form()->closeTag(); ?>
                
            </div>
        </div>
    </div>
</div>
