<h1>Tipo de vínculo cadastrados</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tipo de vínculo</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->tiposVinculo as $tipoVinculo): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($tipoVinculo->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($tipoVinculo->getDescricao()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/tipo-vinculo', ['action' => 'save', 'id' => $tipoVinculo->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/tipo-vinculo', ['action' => 'delete', 'id' => $tipoVinculo->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->tiposVinculo, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/tipo-vinculo']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/tipo-vinculo/save">Novo registro</a>
</div>
