
<form method="get" action="/sig-rh/convenio/index">
    <div class="row" style="padding-top: 10px;">
        <div class="col-md-5">
            <input class="form-control" type="text" name="search" placeholder="Digite aqui para pesquisar" id="numeroContrato" value="<?php echo (null != $this->search) ? $this->search : ''; ?>">
            <select class="form-control" name="tipo" id="tipo">
                <option value="">Todos Tipos</option>
                <?php foreach ($this->lista_tipo as $id => $value) { ?>
                    <option value="<?php echo $id; ?>" <?php echo $id == $this->tipo ? "selected" : ""; ?> ><?php echo $value; ?></option>
                <?php } ?>
            </select>             



        </div>
        <div class="col-md-3">
            <input type="text" name="data_ini" class="date form-control " size="12"  maxlength="40" value="<?php echo $data_ini ; ?>" placeholder="Périodo Início"/>
            
        </div>
        <div class="col-md-3">
            <input type="text" name="data_fim" class="date form-control " size="12"  maxlength="40" value="<?php echo $data_fim; ?>" placeholder="Périodo Fim"/>
        </div>
        <div class="col-md-1">
            <button class="btn-primary btn-sm" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </div>
    </div>
</form>

<div class="row titulo" >
</div>


<h1>Convênios cadastrados</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Número do convênio</th>
                <th>Início convênio</th>
                <th>Término convênio</th>
                <th>Nome responsável</th>
                <th>Cargo responsável</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->convenios as $convenio): ?>
                <tr>
                    <td><?= $this->escapeHtml($this->lista_tipo[$convenio->getTipo()]); ?></td>
                    <td><?= $this->escapeHtml($convenio->getConvenioNumero()); ?></td>
                    <td><?php echo $this->escapeHtml(null != $convenio->getConvenioInicio() ? $convenio->getConvenioInicio()->format("d/m/Y") : ''); ?></td>
                    <td><?php echo $this->escapeHtml(null != $convenio->getConvenioTermino() ? $convenio->getConvenioTermino()->format("d/m/Y") : ''); ?></td>
                    <td><?= $this->escapeHtml($convenio->getResponsavelNome()); ?></td>
                    <td><?= $this->escapeHtml($convenio->getResponsavelCargo()); ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?= $this->url('sig-rh/convenio', ['action' => 'save', 'id' => $convenio->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?= $this->url('sig-rh/convenio', ['action' => 'delete', 'id' => $convenio->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?= $this->paginationControl($this->convenios, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/convenio']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/convenio/save">Novo
        registro</a>
</div>




