<h1>Estatísticas</h1>
<?php if (null == $this->tipoVinculo):?>
    <div class="row alert-danger">
        <p>Preencha os campos Vínculo, Início e Final do período na tela anterior para obter as estatísticas.</p>
    </div>
<?php else:?>
    <h4>Total de colaboradores do tipo <?php echo $this->tipoVinculo->getDescricao();?> no período de <?php echo $this->array_meses[$this->mesIni];?> de <?php echo $this->anoIni;?> até <?php echo $this->array_meses[$this->mesFim];?> de <?php echo $this->anoFim;?>  </h4>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <table class="table table-striped table-condensed ">
        <thead>
            <tr>
                <th>Mês/ano</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->estatisticas as $k => $estatistica):
                $mes = substr($k, 4, 2);
                $ano = substr($k, 0, 4);
            ?>
                <tr>
                    <td><?php echo $this->escapeHtml($this->array_meses[$mes]."/".$ano); ?></td>
                    <td><?php echo $this->escapeHtml($estatistica); ?></td>
                </tr>
            <?php endforeach; ?>
                <tr>
                    <td>Total</td>
                    <td><?php echo (null != $this->total) ? $this->escapeHtml($this->total) : "";?></td>
                </tr>
    </table>
    </div>
</div>
<?php endif;?>
