<div class="row">
    <div class="col-sm-12">
        <br><button class="btn btn-default" onclick="print()" type="submit"><span class="glyphicon glyphicon-print" aria-hidden="true"></span>Imprimir</button>
        
        <table class="table table-striped table-condensed ">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Matrícula</th>
                <th>Grau de instrução</th>
                <th>Obrigatório</th>
<!--                <th>Data início </th>
                <th>Data fim</th>-->
                <th>Data de nascimento</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($colaboradores as $colaborador): 
?>            
                <tr>
                    <td><?php echo $this->escapeHtml($colaborador->nome); ?></td>
                    <td><?php echo $this->escapeHtml($colaborador->matricula); ?></td>
                    <td><?php echo (null != $colaborador->getGrauInstrucao())? $this->escapeHtml($colaborador->getGrauInstrucao()->getDescricao()) : "";?></td>
                    <td><?php echo ($colaborador->getVinculos()->count() > 0) ? $colaborador->getVinculos()->last()->getObrigatorio() ? "Sim" : "Não" : "-"; ?></td>
<!--                    <td><?php //echo $this->escapeHtml(dataInicio); ?></td>
                    <td><?php //echo $this->escapeHtml(dataTermino); ?></td>-->
                    <td><?php echo (null != $colaborador->getDataNascimento()) ? $this->escapeHtml($colaborador->getDataNascimento()->format("d/m/Y")) : "";?></td>
                </tr>
            <?php endforeach; ?>
    </table>
    </div>
</div>
       
</div>
