<form action="/sig-rh/rel-colaborador/gerar-html" method="get">
    <br>    
<div class="row">
    <div class="col-sm-5 form-group" >
        <label for="nome">Nome:</label>                
        <input type="text" name="nome" id="nome" class="form-control" size="12"  maxlength="40" value="<?php echo (!empty($search["nome"])) ? $search["nome"] : "";?>" placeholder="Nome"/>
    </div>
    
    <div class="col-sm-3 form-group" >
        <label for="matricula">Matrícula:</label>                
        <input type="text" name="matricula" id="matricula" class="form-control" size="12"  maxlength="40" value="<?php echo (!empty($search["matricula"])) ? $search["matricula"] : "";?>" placeholder="Matrícula"/>
    </div>
    
    <div class="col-sm-2 form-group">
        <label for="tipoVinculo">Tipo de vínculo: </label>
        <select name="tipoVinculo" id="tipoVinculo" class="form-control">
            <option value="">Selecione aqui...</option>
               <?php foreach($this->array_tipo_vinculo as $row) { ?>
            <option value="<?php echo $row["id"]; ?>"  
                       <?php if ( (!empty($search["tipoVinculo"])) && ($row["id"] == $search["tipoVinculo"]) ){ echo "selected";}?>
            ><?php echo $row["descricao"]; ?></option>
             <?php } ?>
        </select>                      
    </div>
    
    <div class="col-sm-2 form-group">
        <label for="ativo">Ativo: </label>
            <select name="ativo" id="ativo" class="form-control">
                <option value="S">Sim</option>
                <option value="N">Não</option>
                <option value="">Todos</option>
           </select>                      
    </div>
</div>
    <div class="row">
        <div class="col-sm-3 form-group" >
                     <label>Grupo sanguíneo: </label>
                                    <select name="combo_grupoSanguineo" class="form-control">
                                     <option value="">Selecione aqui...</option>
                                     <?php foreach($this->array_grupoSanguineo as $row) { ?>
                                        <option value="<?php echo $row["id"]; ?>"  
                                                 <?php if ( (!empty($search["combo_grupoSanguineo"])) && ($row["id"] == $search["combo_grupoSanguineo"])){ echo "selected";}?>
                                                ><?php echo $row["nome"]; ?></option>
                                     <?php } ?>
                                   </select>                      
        </div>
    
        <div class="col-sm-3 form-group" >
                     <label>Grau de instrução: </label>
                                    <select name="combo_grauInstrucao" class="form-control">
                                     <option value="">Selecione aqui...</option>
                                     <?php foreach($this->array_grauInstrucao as $row) { ?>
                                        <option value="<?php echo $row["id"]; ?>"  
                                                 <?php if ( (!empty($search["combo_grauInstrucao"])) && ($row["id"] == $search["combo_grauInstrucao"])){ echo "selected";}?>
                                                ><?php echo $row["nome"]; ?></option>
                                     <?php } ?>
                                   </select>                      
        </div>
    
        <div class="col-sm-2 form-group" >
        <label>Necessidades especiais: </label>
            <select name="necessidadeEspecial" class="form-control">
                <option value="">Selecione aqui...</option>
                <option value="0" <?php if ( (!empty($search["necessidadeEspecial"])) && ("0" == $search["necessidadeEspecial"])) { echo "selected";}?>>Não</option>
                <option value="1" <?php if ( (!empty($search["necessidadeEspecial"])) && ("1" == $search["necessidadeEspecial"])) { echo "selected";}?>>Sim</option>
            </select>                      
        </div>
        
        <div class="col-sm-2 form-group" >
            <label for="sexo">Sexo: </label>
            <select name="sexo" id="sexo" class="form-control">
                <option value="">Selecione aqui...</option>
                <option value="F" <?php if ( (!empty($search["sexo"])) && ("F" == $search["sexo"])) { echo "selected";}?>>Feminino</option>
                <option value="M" <?php if ( (!empty($search["sexo"])) && ("M" == $search["sexo"])){ echo "selected";}?>>Masculino</option>
            </select>                      
        </div>
    
        <div class="col-sm-2 form-group" >
            <label for="combo_estadoCivil">Estado civil: </label>
                <select name="combo_estadoCivil" id="combo_estadoCivil" class="form-control">
                    <option value="">Selecione aqui...</option>
                     <?php foreach($this->array_estadoCivil as $row) { ?>
                           <option value="<?php echo $row["id"]; ?>"  
                                    <?php if ( (!empty($search["combo_estadoCivil"])) && ($row["id"] == $search["combo_estadoCivil"])){ echo "selected";}?>
                                   ><?php echo $row["nome"]; ?></option>
                        <?php } ?>
                </select>                      
        </div>
        
    </div>
    
    <div class="row">
            <div class="col-sm-3 form-group">
                <label for="inicioVigenciaIni">Início vigência (início do período):</label>
                <input class="form-control" type="date" value="" name="inicioVigenciaIni" id="inicioVigenciaIni"> 
            </div>

            <div class="col-sm-3 form-group">
                <label for="inicioVigenciaFim">Início vigência (final do período):</label>
                <input class="form-control" type="date" value="" name="inicioVigenciaFim" id="inicioVigenciaFim"> 
            </div>

            <div class="col-sm-3 form-group">
                <label for="terminoVigenciaIni">Término vigência (início do período):</label>
                <input class="form-control" type="date" value="" name="terminoVigenciaIni" id="terminoVigenciaIni"> 
            </div>

            <div class="col-sm-3 form-group">
                <label for="terminoVigenciaFim">Término vigência (final do período):</label>
                <input class="form-control" type="date" value="" name="terminoVigenciaFim" id="terminoVigenciaFim"> 
            </div>
    </div>

    <div class="row">
        <div class="col-sm-2 form-group" >
                 <label for="obrigatorio">Obrigatório: </label>
                         <select name="obrigatorio" id="obrigatorio" class="form-control">
                                 <option value="">Selecione aqui...</option>
                                 <option value="9" <?php if ( (!empty($search["obrigatorio"])) && ( "0" == $search["obrigatorio"])) { echo "selected";}?>>Não</option>
                                 <option value="1" <?php if ( (!empty($search["obrigatorio"])) && ("1" == $search["obrigatorio"])) { echo "selected";}?>>Sim</option>
                         </select>                      
        </div>
        
        <div class="col-sm-2 form-group" >
                     <label for="nivel">Nível de escolaridade: </label>
                                    <select name="nivel" id="nivel" class="form-control">
                                     <option value="">Selecione aqui...</option>
                                     <?php foreach($this->array_nivelEscolaridade as $row) { ?>
                                        <option value="<?php echo $row["id"]; ?>"  
                                                 <?php if ( (!empty($search["nivel"]))  && ($row["id"] == $search["nivel"])) { echo "selected";}?>
                                                ><?php echo $row["nome"]; ?></option>
                                     <?php } ?>
                                   </select>                      
        </div>
        
        <div class="col-sm-3 form-group" >
                     <label for="instituicaoFomento">Instituicao de fomento: </label>
                                    <select name="instituicaoFomento" id="instituicaoFomento" class="form-control">
                                     <option value="">Selecione aqui...</option>
                                     <?php foreach($this->array_fomento as $row) { ?>
                                        <option value="<?php echo $row["id"]; ?>"  
                                                 <?php if ( (!empty($search["instituicaoFomento"]))  && ( $row["id"] == $search["instituicaoFomento"])){ echo "selected";}?>
                                                ><?php echo $row["desRazaoSocial"]; ?></option>
                                     <?php } ?>
                                   </select>                      
        </div>
        
        <div class="col-sm-2 form-group">
                     <label for="modalidadeBolsa">Modalidade Bolsa: </label>
                    <select name="modalidadeBolsa" id="modalidadeBolsa" class="form-control">
                        <option value="">Selecione aqui...</option>
                        <?php foreach($this->array_bolsa as $row) { ?>
                           <option value="<?php echo $row["id"]; ?>"  
                                    <?php if ( (!empty($search["modalidadeBolsa"])) && ($row["id"] == $search["modalidadeBolsa"]) ){ echo "selected";}?>
                                   ><?php echo $row["nome"]; ?></option>
                        <?php } ?>
                   </select>                      
        </div>
        <div class="col-sm-3 form-group">
            <label for="aniversariantesMes">Aniversariantes do mês:</label>
                <select name="aniversariantesMes" id="aniversariantesMes" class="form-control">
                    <option value="">Selecione aqui...</option>
                        <?php foreach($this->array_meses as $k => $value) { ?>
                           <option value="<?php echo $k; ?>"  
                                    <?php if ( (!empty($search["aniversariantesMes"])) && ($k == $search["aniversariantesMes"]) ){ echo "selected";}?>
                                   ><?php echo $value; ?></option>
                        <?php } ?>
                </select>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-4 form-group" >
             <label for="orientador">Supervisor/Orientador: </label>
                    <select name="orientador" id="orientador" class="form-control">
                     <option value="">Selecione aqui...</option>
                     <?php foreach($this->array_orientador as $row) { ?>
                        <option value="<?php echo $row["matricula"]; ?>"  
                                 <?php if ( (!empty($search["orientador"]))  && ( $row["matricula"] == $search["orientador"])){ echo "selected";}?>
                                ><?php echo $row["nome"]; ?></option>
                     <?php } ?>
                   </select>                      
        </div>
    
        <div class="col-sm-3 form-group" >
                     <label for="subLotacao">Sublotação: </label>
                                    <select name="subLotacao" id="subLotacao" class="form-control">
                                     <option value="">Selecione aqui...</option>
                                     <?php foreach($this->array_subLotacao as $row) { ?>
                                        <option value="<?php echo $row["id"]; ?>"  
                                                 <?php if ( (!empty($search["subLotacao"]))  && ( $row["id"] == $search["subLotacao"])){ echo "selected";}?>
                                                ><?php echo $row["descricao"]; ?></option>
                                     <?php } ?>
                                   </select>                      
        </div>
        <div class="col-sm-3 form-group" >
                    <label for="contratoVencido">Contrato vencido: </label>
                                <select name="contratoVencido" id="contratoVencido" class="form-control">
                                 <option value="">Não</option>
                                 <option value="1">Sim</option>
                               </select>                      
        </div>


    </div>

    <div class="row">
       <div class="col-sm-3 form-group" style="padding-top: 25px;">                  
                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Relatório</button>
                <br/>
                <br/>
                <button type="submit" formaction="/sig-rh/rel-colaborador/csv">CSV</button>                    
        </div>
        
    </div>
</form>



