<h1>Vigência</h1>
  
    <h4>Total de colaboradores com data de vigência</h4>
<div class="row">
    <div class="col-sm-12">
        <hr>
        <table class="table table-striped table-condensed ">
        <thead>
            <tr>
                <th>Matrícula</th>
                <th>Nome</th>
                <th>Data de vigência</th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->colaboradores as $colaborador): 

                $vinculos = $colaborador->getVinculos();
                $vigencia = (isset($vinculos[0])) ? $vinculos[0]->getVigencia() : null;

            ?>
                <tr>
                   <td><?php echo $this->escapeHtml($colaborador->matricula); ?></td>
                   <td><?php echo $this->escapeHtml($colaborador->nome); ?></td>
                   <td><?php echo ($vigencia != null) ?$this->escapeHtml($vigencia->format('d/m/Y')): '';?> </td>
                </tr>
            <?php endforeach; ?>

    </table>
    </div>
</div>


    
