<script src="/js/inputmask.js"></script>
<script src="/js/jquery.inputmask.js"></script>

<?php
if ($this->nome == "") {
    $this->nome = null;
}
if (null == $folhasPonto):?>
<h1>Folhas de ponto dos estudantes</h1>
<form method="get" action="/sig-rh/folha-ponto/index">
    <div class="row">
        <div class="col-md-2">
            <label for="referencia">Referência (mês/ano)</label>
            <input pattern="(0[1-9]|1[012]).[0-9]{4}" title="Referência (mm/aaaa)" class="form-control" type="text" name="referencia" id="referencia" value="<?php echo (null != $this->referencia) ? $this->referencia : ''; ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" class="btn btn-sm" value="Enviar">
        </div>
    </div>
<?php
else:
    $status = [0 => "<span class='label label-danger'>Aguardando processamento.</span>",
               1 => "<span class='label label-warning'>Justificativas pendentes.</span>",
               2 => "<span class='label label-success'>Finalizada.</span>",
               10 => "<span class='label label-info'>Treinando.</span>",
        ];?>
    <h1>Folhas de ponto dos estudantes - <?php echo $this->stringReferencia;?> </h1>
    <div class="row">
        <h3 class="panel-title">
            <a class="btn btn-secondary btn-sm pull-right" href="/sig-rh/folha-ponto" title="Fechar"><span class="glyphicon glyphicon-remove"></span></a>
        </h3>
    </div>

    <form method="get" action="/sig-rh/folha-ponto/index">
        <div class="row">
            <div class="col-md-3">
                <input type="text" name="nome" id="nome" placeholder="Digite o nome aqui para pesquisar" class="form-control" value="<?php echo $this->nome;?>">
                <input type="hidden" name="referencia" value="<?php echo $this->referencia; ?>">
            </div>
            <div class="col-md-3">
                <input type="text" name="instituicaoFomento" id="instituicaoFomento" placeholder="Digite a instituição de fomento aqui para pesquisar" class="form-control" value="<?php echo $this->instituicaoFomento;?>">
            </div>
            <div class="col-md-3">
                <input type="text" name="orientador" id="orientador" placeholder="Digite o orientador aqui para pesquisar" class="form-control" value="<?php echo $this->orientador;?>">
            </div>
            <div class="col-md-2">
                <select name="status" id="status" class="form-control">
                    <option value="" <?php echo ($this->status == '') ? "selected" : "";?>>Selecione o status</option>
                    <option value="0" <?php echo ($this->status == '0') ? "selected" : "";?>>Aguardando processamento.</option>
                    <option value="1" <?php echo ($this->status == '1') ? "selected" : "";?>>Justificativas pendentes.</option>
                    <option value="2" <?php echo ($this->status == '2') ? "selected" : "";?>>Finalizada.</option>
                    <option value="10" <?php echo ($this->status == '10') ? "selected" : "";?>>Treinando.</option>
                </select>
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
    </form>

<hr>    
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Colaborador</th>
                <th>Instituição de fomento</th>
                <th>Orientador</th>
                <th>Status</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->folhasPonto as $folhaPonto): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($folhaPonto->getColaboradorMatricula()->getNome()); ?></td>
                    <td><?php echo (null != $folhaPonto->getColaboradorMatricula()->getVinculos()->first()->getInstituicaoFomento()) ? $this->escapeHtml($folhaPonto->getColaboradorMatricula()->getVinculos()->first()->getInstituicaoFomento()->getDesRazaoSocial()) : "";?></td>
                    <td><?php echo $this->escapeHtml($folhaPonto->getColaboradorMatricula()->getVinculos()->first()->getOrientador()->getNome());?></td>
                    <td><?php echo $status[$folhaPonto->getStatus()];?></td>
                    <td>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'processar', 'id' => $folhaPonto->getId(), 'referencia' => $this->referencia, 'nomePesquisa' => ('' != $this->nome ) ? str_replace(" ", "_", $this->nome) : null, 'restrito' => 0, 'page' => $this->page]) ?>"
                           title="Processar folha ."><span class="glyphicon glyphicon-dashboard"></span></a>
                           
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'registros', 'id' => $folhaPonto->getId(), 'referencia' => $this->referencia, 'nomePesquisa' => ('' != $this->nome ) ? str_replace(" ", "_", $this->nome) : null, 'restrito' => 0, 'page' => $this->page]) ?>"
                           title="Visualizar folha ponto."><span class="glyphicon glyphicon-list-alt"></span></a>
                           
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'impressao', 'id' => $folhaPonto->getId(), 'referencia' => $this->referencia, 'nomePesquisa' =>  ('' != $this->nome ) ? str_replace(" ", "_", $this->nome) : null, 'restrito' => 0, 'page' => $this->page]) ?>"
                           title="Imprimir folha ponto."><span class="glyphicon glyphicon-print"></span></a>
                           
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->folhasPonto, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/folha-ponto']); ?>
    </span>
</div>

    <div class="row">
        <div class="btn-toolbar">
            <a class="btn btn-primary pull-left" href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'processar', 'id' => '0', 'referencia' => $this->referencia, 'page' => $this->page]);?>">Processar todas</a>
            <a class="btn btn-primary pull-left" href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'impressao', 'id' => '0', 'referencia' => $this->referencia, 'page' => $this->page]);?>">Imprimir todas</a>
        </div>
    </div>
</form>
<?php endif;?>
<script>
    $("#referencia").inputmask("99/9999");
</script>
