<script src="/js/inputmask.js"></script>
<script src="/js/jquery.inputmask.js"></script>

<h1>Folhas de ponto dos estudantes</h1>
<?php
if ($this->nome == "") {
    $this->nome = null;
}
if (null == $folhasPonto):?>
<form method="get" action="/sig-rh/folha-ponto/index">
    <div class="row">
        <div class="col-md-2">
            <label for="referencia">Referência (mês/ano)</label>
            <input pattern="(0[1-9]|1[012]).[0-9]{4}" title="Referência (mm/aaaa)" class="form-control" type="text" name="referencia" id="referencia" value="<?php echo (null != $this->referencia) ? $this->referencia : ''; ?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" class="btn btn-sm" value="Enviar">
        </div>
    </div>
<?php
else:
    $status = [0 => "<span class='label label-danger'>Aguardando processamento.</span>",
               1 => "<span class='label label-warning'>Justificativas pendentes.</span>",
               2 => "<span class='label label-success'>Finalizada.</span>",
               10 => "<span class='label label-info'>Treinando.</span>",
        ];?>
    <div class="row">
        <h3 class="panel-title">
            <a class="btn btn-secondary btn-sm pull-right" href="/sig-rh/folha-ponto" title="Fechar"><span class="glyphicon glyphicon-remove"></span></a>
        </h3>
    </div>

    <form method="get" action="/sig-rh/folha-ponto/index">
        <div class="row">
            <div class="col-md-5">
                <input type="text" name="nome" id="nome" placeholder="Digite o nome aqui para pesquisar" class="form-control" value="<?php echo $this->nome;?>">
                <input type="hidden" name="referencia" value="<?php echo $this->referencia; ?>">
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search"></span></button>
            </div>

            <div class="col-md-6 text-right">
                <b>Referência: <?php echo $this->stringReferencia; ?></b>
            </div>

        </div>
    </form>

<hr>    
<div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Colaborador</th>
                <th>Orientador</th>
                <th>Status</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->folhasPonto as $folhaPonto): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($folhaPonto->getColaboradorMatricula()->getNome()); ?></td>
                    <td><?php echo $this->escapeHtml($folhaPonto->getColaboradorMatricula()->getVinculos()->last()->getOrientador()->getNome());?></td>
                    <td><?php echo $status[$folhaPonto->getStatus()];?></td>
                    <td>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'processar', 'id' => $folhaPonto->getId(), 'referencia' => $this->referencia, 'nomePesquisa' => $this->nome, 'page' => $this->page]) ?>"
                           title="Processar folha ."><span class="glyphicon glyphicon-dashboard"></span></a>
                           
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'registros', 'id' => $folhaPonto->getId(), 'referencia' => $this->referencia, 'nomePesquisa' => $this->nome, 'page' => $this->page]) ?>"
                           title="Visualizar folha ponto."><span class="glyphicon glyphicon-list-alt"></span></a>
                           
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?php echo $this->paginationControl($this->folhasPonto, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/folha-ponto']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="<?php echo $this->url('sig-rh/folha-ponto', ['action' => 'processar', 'id' => '0', 'referencia' => $this->referencia, 'page' => $this->page]);?>">Processar todas</a>
</div>
</form>
<?php endif;?>
<script>
    $("#referencia").inputmask("99/9999");
</script>
