<?php $this->headScript()->appendFile('/js/folha-ponto-registros.js', 'text/javascript'); ?>

<h1>Folha ponto</h1>

<?php

if ($this->folhaPonto != null):    
    $mesesAno = ["1" => "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
    $diasSemana = [0 => "Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"];
    $tipoRegistro = ["A" => "*", "C" => "", "M" => "!"];

    $movimentacoesPonto = $this->folhaPonto->getMovimentacaoPonto();
    $ano = substr($this->folhaPonto->getReferencia(), 0, 4);
    $mes = substr($this->folhaPonto->getReferencia(), 4, 2);

    $saldoMinutosTotal = $this->folhaPonto->getSaldoMinutos();
    if($saldoMinutosTotal < 0) {
        $horasSaldoTotal = sprintf('%03d', intdiv($saldoMinutosTotal, 60));
    } else {
        $horasSaldoTotal = sprintf('%02d', intdiv($saldoMinutosTotal, 60));
    }
    $minutosSaldoTotal = sprintf('%02d', ($saldoMinutosTotal % 60));
?>

    <hr>
    <div class="row">
        <div class="col-md-6 panel-title">
            <a href="/sig-rh/colaborador/save/<?php echo $this->folhaPonto->getColaboradorMatricula()->getMatricula(); ?>">
            <?php echo $this->escapeHtml($this->folhaPonto->getColaboradorMatricula()->getMatricula()." - ".$this->folhaPonto->getColaboradorMatricula()->getNome()); ?></a>
        </div>
        <div class="col-md-3 panel-title">
            <span class="pull-left">Referência: <?php echo $mesesAno[(int)$mes]."/".$ano;?></span>
        </div>
        <div class="col-md-2 panel-title">
            <span class="pull-right">Saldo: <?php echo $horasSaldoTotal.":".$minutosSaldoTotal;?>hs</span>
        </div>
        <div class="col-md-1 panel-title"> 
            <?php 
                if ($this->restrito == 1) {
                    $urlFechar= "/sig-rh/folha-ponto/estudante?page=".$this->page; 
                } else {
                    $urlFechar= "/sig-rh/folha-ponto?nome=".$this->nome."&referencia=".$this->referencia."&page=".$this->page;
                }
            ?>
            <a class="btn btn-secondary btn-sm pull-right" href="<?php echo $urlFechar;?>" title="Fechar"><span class="glyphicon glyphicon-remove"></span></a>
        </div>
    </div>
    <hr>
    
    <div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Data</th>
                <th>Dia da semana</th>
                <th>Hora do registro</th>
                <th>Total de horas no dia</th>
                <th>Observações</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($movimentacoesPonto as $movimentacaoPonto):
                $dataPonto = \DateTime::createFromFormat("Ymd", $folhaPonto->getReferencia().$movimentacaoPonto->getDiaPonto());
                $dataPonto->setTime(0, 0);
                $expediente = true;
            
                if( ($dataPonto->format('w') == 0) || ($dataPonto->format('w') == 6) || (isset($this->feriadosPeriodo[$dataPonto->format("d")])) ) {
                    $expediente = false;
                    ?>
                    <tr style="background-color: #F0FFFF;">
                    <?php } else {?>
                        <tr>
                    <?php }?>
                <td><?php echo $this->escapeHtml($dataPonto->format("d/m/Y"));?></td>
                <td><?php echo $this->escapeHtml($diasSemana[$dataPonto->format("w")]); ?></td>
                <td><?php foreach($movimentacaoPonto->getRegistros() as $registro):
                    echo $this->escapeHtml($registro->getHoraRegistro()->format("H:i").$tipoRegistro[$registro->getTipo()]. " ");
                    endforeach;?>
                </td>
                <td>
                    <?php 
                        if($expediente) {
                            $saldoMinutos = $movimentacaoPonto->getSaldoMinutos();
                            if($saldoMinutos < 0) {
                                $horasSaldo = sprintf('%03d', intdiv($saldoMinutos, 60));
                            } else {
                                $horasSaldo = sprintf('%02d', intdiv($saldoMinutos, 60));
                            }
                            $minutosSaldo = sprintf('%02d', ($saldoMinutos % 60));
                            echo $horasSaldo.":".$minutosSaldo;
                        }
                    ?>
                </td>
                <td><?php 
                    if (isset($this->feriadosPeriodo[$dataPonto->format("d")])):
                        echo "<font class='alert-info'><strong>-Feriado: ".$this->feriadosPeriodo[$dataPonto->format("d")]->getNome()."</strong></font><br>";
                    endif;
                    $ocorrenciaId = null;
                    foreach($movimentacaoPonto->getOcorrencias() as $ocorrencia):
                        echo (null == $ocorrencia->getJustificativa1() && null == $ocorrencia->getJustificativa2()) ? "<font class='alert-danger'>" : "<font class='alert-warning'>";
                        echo "<strong>";
                        echo str_replace(". -", ".<br>-", $ocorrencia->getDescricao());
                        echo "</strong></font>";
    
                        $ocorrenciaId = $ocorrencia->getId();
                        echo (null != $ocorrencia->getJustificativa1()) ? "<br><font class='alert-success'>(".$ocorrencia->getJustificativa1()->getDescricao().")</font>" : "";
                        echo (null != $ocorrencia->getJustificativa2()) ? "<br><font class='alert-success'>(".$ocorrencia->getJustificativa2()->getDescricao().")</font>" : "";
                    endforeach;
                    ?>
                </td>
                <td><?php 
                    if($ocorrenciaId != null):?>
                        <button type="button" class="btn btn-sm btn-primary pull-left" data-toggle="tooltip" data-placement="top" title="Justificar ocorrência." onclick="novaJustificativa('<?php echo $ocorrenciaId;?>')">
                            <span class="glyphicon glyphicon-copy"></span>
                        </button>
                    <?php endif;
                    if ($expediente):?>
                        <button type="button" class="btn btn-sm btn-primary pull-right" data-toggle="tooltip" data-placement="top" title="Incluir/excluir registro de horário." onclick="incluirHorario('<?php echo $movimentacaoPonto->getId();?>')">
                                    <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach;?>

        </tbody>
        </table>
    </div>
<?php endif; ?>

<div class="modal fade " id="JustificativaModal" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Justificar ocorrência</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" onclick="fncSalvarJustificativa(this)">Salvar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade " id="IncluirHorarioModal" data-backdrop="static">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Incluir novo registro de horário</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" onclick="fncSalvarHorario(this)">Salvar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->