<h1>Registro das batidas de ponto</h1>
<form method="get" action="/sig-rh/batida-ponto/index">
    <div class="row">
        <div class="col-md-2">
            <label for="matricula">Matrícula</label>
            <input class="form-control" type="text" name="matricula" id="matricula" value="<?php echo (null != $this->colaborador) ? $this->colaborador->getMatricula() : '';?>">
        </div>
        <div class="col-md-2">
            <label for="periodoMovimentacao">Período (mês/ano)</label>
            <input class="form-control" type="text" name="periodoMovimentacao" id="periodoMovimentacao" value="<?php echo (null != $this->periodoMovimentacao) ? $this->periodoMovimentacao : '';?>">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" class="btn btn-sm" value="Enviar">
        </div>
    </div>
</form>
<?php if ($this->batidasPonto != null):
    
$diasSemana = [0 => "Domingo", 1 => "Segunda-feira", 2 => "Terça-feira", 3 => "Quarta-feira", 4 => "Quinta-feira", 5 => "Sexta-feira", 6 => "Sábado"];    
    
?>
    <hr>
    <h3><a href="/sig-rh/colaborador/save/<?php echo $this->colaborador->getMatricula();?>">
        <?php echo $this->escapeHtml($this->colaborador->getNome()); ?></a>
    </h3>
    <hr>

    <div class="row">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Dia da semana</th>
                        <th>Hora</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->batidasPonto as $batida): ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($batida->getDataBatida()->format("d/m/Y")); ?></td>
                            <td><?php echo $this->escapeHtml($diasSemana[$batida->getDataBatida()->format("w")]); ?></td>
                            <td><?php foreach($batida->getHorarios() as $k => $horario):
                                    echo $this->escapeHtml($horario->getHoraBatida()->format("H:i"))." ";
                                endforeach;
                            ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <span class="pull-right">
                <?php echo $this->paginationControl($this->batidasPonto, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/batida-ponto', 'matricula' => $colaborador->getMatricula()]); ?>
            </span>
        </div>
    <?php endif;?>
