
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Acesso Restrito</h3>
            </div>
            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>

                <div class="col-sm-12">
                    <?php
                    echo $this->formLabel($form->get('nome'));
                    echo $this->formInput($form->get('nome'));
                    ?>
                </div>
                <div class="col-sm-12">
                    <?php
                    echo $this->formLabel($form->get('senha'));
                    echo $this->formInput($form->get('senha'));
                    ?>
                </div>
                <div class="col-sm-12" style="margin-top: 20px">
                    <?php
                    echo $this->formInput($form->get('submit'));
                    ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>

    </div>
    <div class="col-sm-4"></div>
</div>    
