<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Início</th>
            <th>Previsão conclusão</th>
            <th>Nível</th>
            <th>Curso</th>
            <th>Semestre</th>
            <th>Início efetivo</th>
            <th>Fonte seguro</th>
            <th>Apólice seguro</th>
            <th>Seguradora</th>
            <th>Instituição</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->estagios as $estagio): ?>
            <tr>
                <td><?= $this->escapeHtml($estagio->getInicio()); ?></td>
                <td><?= $this->escapeHtml($estagio->getPrevisaoConclusao()); ?></td>
                <td><?= $estagio->getNivel()?$this->escapeHtml($estagio->getNivel()->getDescricao()):""; ?></td>
                <td><?= $estagio->getCurso()?$this->escapeHtml($estagio->getCurso()->getDescricao()):""; ?></td>
                <td><?= $this->escapeHtml($estagio->getSerie()); ?></td>
                <td><?php echo $this->escapeHtml(null!= $estagio->getDataInicioEfetivo() ? $estagio->getDataInicioEfetivo()->format("d/m/Y"): ''); ?></td>
                <td><?= $estagio->getFonteSeguro()?$this->escapeHtml($estagio->getFonteSeguro()->getDescricao()):""; ?></td>
                <td><?= $this->escapeHtml($estagio->getSeguroApolice()); ?></td>
                <td><?= $this->escapeHtml($estagio->getSeguroSeguradora()); ?></td>
                <td><?= $this->escapeHtml($estagio->getInstituicao()->getDesRazaoSocial()); ?></td>
                
                <td><button type="button" class="btn btn-primary btn-sm pull-center"
                       onclick="editarEstagio('<?php echo $estagio->getId();?>')"
                       title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></button>
                    <a class="btn btn-primary btn-sm pull-center"
                       href="<?= $this->url('sig-rh/estagio', ['action' => 'delete', 'id' => $estagio->getId()]) ?>"
                       title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<span class="pull-right">
    <?= $this->paginationControl($this->estagios, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/estagio']); ?>
</span>
