<h1>Estágios cadastrados</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
            <th>Id</th>
            <th>Início</th>
            <th>Previsão ano conclusão</th>
            <th>Série</th>
            <th>Seguro apólice</th>
            <th>Seguro seguradora</th>
            <th>Seguro mensalidade</th>
            <th>Seguro capital</th>
            <th>Nível</th>
            <th>Curso</th>
            <th>Fonte seguro</th>
            <th>Opções</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->estagios as $estagio): ?>
            <tr>
                <td><?= $this->escapeHtml($estagio->getId()); ?></td>
                <td><?= $this->escapeHtml($estagio->getAnoInicio()); ?></td>
                <td><?= $this->escapeHtml($estagio->getAnoPrevisaoConclusao()); ?></td>
                <td><?= $this->escapeHtml($estagio->getSerie()); ?></td>
                <td><?= $this->escapeHtml($estagio->getSeguroApolice()); ?></td>
                <td><?= $this->escapeHtml($estagio->getSeguroSeguradora()); ?></td>
                <td><?= $this->escapeHtml($estagio->getseguroMensalidade()); ?></td>
                <td><?= $this->escapeHtml($estagio->getSeguroCapital()); ?></td>
                <td><?= $this->escapeHtml($estagio->getNivel()->getNivel()); ?></td>
                <td><?= $this->escapeHtml($estagio->getCurso()->curso); ?></td>
                <td><?= $this->escapeHtml($estagio->getFonteSeguro()->fonteSeguro); ?></td>
                
                <td><a class="btn btn-primary btn-sm pull-center"
                       href="<?= $this->url('sig-rh/estagio', ['action' => 'save', 'id' => $estagio->getId()]) ?>"
                       title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-primary btn-sm pull-center"
                       href="<?= $this->url('sig-rh/estagio', ['action' => 'delete', 'id' => $estagio->getId()]) ?>"
                       title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?= $this->paginationControl($this->estagios, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/estagio']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/estagio/save">Novo
        registro</a>
</div>
