<?= $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-md-12">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. 
                </h3>
              <div class="col-md-3">

                <?php echo $this->formLabel($this->form->get('anoInicio')); ?><br>
                <?php echo  $this->formElement($this->form->get('anoInicio')); ?>
                <?php echo  $this->formElementErrors($this->form->get('anoInicio')); ?>  
              </div>

              <div class="col-md-6">
                <?php echo $this->formLabel($this->form->get('anoPrevisaoConclusao')); ?><br>
                <?php echo  $this->formElement($this->form->get('anoPrevisaoConclusao')); ?>
                <?php echo  $this->formElementErrors($this->form->get('anoPrevisaoConclusao')); ?>                  
              </div>

                
              <div class="col-md-4">
                <?php echo  $this->formLabel($this->form->get('serie')); ?><br>
                <?php echo  $this->formElement($this->form->get('serie')); ?>
                <?php echo  $this->formElementErrors($this->form->get('serie')); ?>                  
              </div>
        
              <div class="col-md-4">
                <?php echo  $this->formLabel($this->form->get('dataInicioEfetivo')); ?><br>
                <?php echo  $this->formElement($this->form->get('dataInicioEfetivo')); ?>
                <?php echo  $this->formElementErrors($this->form->get('dataInicioEfetivo')); ?>                  
              </div>


              <div class="col-md-4">
                <?php echo  $this->formLabel($this->form->get('seguroApolice')); ?><br>
                <?php echo  $this->formElement($this->form->get('seguroApolice')); ?>
                <?php echo  $this->formElementErrors($this->form->get('seguroApolice')); ?>                  
              </div>

              <div class="col-md-4">
                <?php //echo  $this->formLabel($this->form->get('seguroApolice')); ?><br>
                <?php //echo $this->formElement($this->form->get('seguroApolice')); ?>
                <?php //echo  $this->formElementErrors($this->form->get('seguroApolice')); ?>                  
              </div>

              <div class="col-md-4">
                <?php echo $this->formLabel($this->form->get('seguroSeguradora')); ?><br>
                <?php echo $this->formElement($this->form->get('seguroSeguradora')); ?>
                <?php echo $this->formElementErrors($this->form->get('seguroSeguradora')); ?>                  
              </div>

              <div class="col-md-4">
                <?php echo  $this->formLabel($this->form->get('seguroMensalidade')); ?><br>
                <?php echo $this->formElement($this->form->get('seguroMensalidade')); ?>
                <?php echo  $this->formElementErrors($this->form->get('seguroMensalidade')); ?>                  
              </div>
        
              <div class="col-md-4">
                <?php echo  $this->formLabel($this->form->get('seguroCapital')); ?><br>
                <?php echo  $this->formElement($this->form->get('seguroCapital')); ?>
                <?php echo  $this->formElementErrors($this->form->get('seguroCapital')); ?>                  
              </div>

        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>