<h1>Justificativas cadastradas</h1>
<div class="row">

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descrição</th>
                <th>Indicar Horário</th>
                <th>Considerar Horas</th>
                <th>Listar para escolha</th>
                <th>Indicar crachá</th>
                <th>Opções</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->justificativas as $justificativa): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($justificativa->getId()); ?></td>
                    <td><?php echo $this->escapeHtml($justificativa->getDescricao()); ?></td>
                    <td><?php echo ($justificativa->getIndicarHorario()) ? "Sim" : "Não"; ?></td>
                    <td><?php echo ($justificativa->getConsiderarHoras()) ? "Sim" : "Não"; ?></td>
                    <td><?php echo ($justificativa->getListar()) ? "Sim" : "Não"; ?></td>
                    <td><?php echo ($justificativa->getIndicarCracha()) ? "Sim" : "Não"; ?></td>
                    <td><a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/justificativa', ['action' => 'save', 'id' => $justificativa->getId()]) ?>"
                           title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></a>
                        <a class="btn btn-primary btn-sm pull-center"
                           href="<?php echo $this->url('sig-rh/justificativa', ['action' => 'delete', 'id' => $justificativa->getId()]) ?>"
                           title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <span class="pull-right">
        <?= $this->paginationControl($this->justificativas, 'Elastic', 'sig-rh/partial/paginator', ['route' => 'sig-rh/justificativa']); ?>
    </span>
</div>

<div class="row">
    <a class="btn btn-primary pull-left" href="/sig-rh/justificativa/save">Novo
        registro</a>
</div>
