<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Número do chip</th>
            <th>Data de inclusão</th>
            <th>Data de exclusão</th>
            <th>Observações</th>
            <th>Ativo</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->crachas as $cracha): ?>
            <tr>
                <td><?php echo $this->escapeHtml($cracha->getNumeroChip()); ?></td>
                <td><?php echo (null != $cracha->getDataInclusao() ? $this->escapeHtml($cracha->getDataInclusao()->format("d/m/Y")) : ""); ?></td>
                <td><?php echo (null != $cracha->getDataExclusao() ? $this->escapeHtml($cracha->getDataExclusao()->format("d/m/Y")) : ""); ?></td>
                <td><?php echo $this->escapeHtml($cracha->getObservacoes()); ?></td>
                <td><?php echo ($cracha->getAtivo() ? "Sim" : "Não"); ?></td>

                <td><button type="button" class="btn btn-primary btn-sm pull-center"
                            onclick="editarCracha('<?php echo $cracha->getId();?>')"
                       title="Editar registro."><span class="glyphicon glyphicon-pencil"></span></button>
                    <button type="button" class="btn btn-primary btn-sm pull-center" 
                               onclick="excluirCracha('<?php echo $cracha->getId();?>')"
                        title="Excluir registro."><span class="glyphicon glyphicon-remove"></span></button>

                </td>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>
