<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ZendXml\\' => array($vendorDir . '/zendframework/zendxml/library'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'DoctrineORMModule\\' => array($vendorDir . '/doctrine/doctrine-orm-module/src'),
    'DoctrineModule\\' => array($vendorDir . '/doctrine/doctrine-module/src'),
    'BjyProfiler' => array($vendorDir . '/bjyoungblood/bjy-profiler/src'),
);
