<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Dia da semana</th>
            <th>Código do Horário</th>
            <th>Entrada 1</th>
            <th>Saída 1</th>
            <th>Entrada 2</th>
            <th>Saída 2</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->horarios as $horario): ?>
            <tr>
                <td><?php echo $this->escapeHtml($this->diasSemana[$horario->getDiaSemana()]); ?></td>
                <td><?php echo $this->escapeHtml($horario->getEscala()->getId()); ?></td>
                <td><?php echo (null != $horario->getEscala()->getEntrada1()) ? $this->escapeHtml($horario->getEscala()->getEntrada1()->format("H:i")) : ""; ?></td>
                <td><?php echo (null != $horario->getEscala()->getSaida1()) ? $this->escapeHtml($horario->getEscala()->getSaida1()->format("H:i")) : ""; ?></td>
                <td><?php echo (null != $horario->getEscala()->getEntrada2()) ? $this->escapeHtml($horario->getEscala()->getEntrada2()->format("H:i")) : ""; ?></td>
                <td><?php echo (null != $horario->getEscala()->getSaida2()) ? $this->escapeHtml($horario->getEscala()->getSaida2()->format("H:i")) : ""; ?></td>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>
