<?= $this->form()->openTag($this->form); ?>
<div class="row">
    <div class="col-md-12">
        <h3 class="panel-title">
            Por favor, preencha o formulário abaixo e, em seguida, clique sobre
            o botão <i>Salvar</i>. 
        </h3>
        <hr>
        <div class="row">
            <div class="col-md-4">
                <label>Dia da Semana</label>
            </div>
            
            <div class="col-md-6">
                <label>Escala</label>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                Segunda-Feira
            </div>
            
            <div class="col-md-6">
                <?php echo $this->formElement($this->form->get('escalaSegunda')); ?>
                <?php echo $this->formElementErrors($this->form->get('escalaSegunda')); ?>  
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                Terça-Feira
            </div>
            
            <div class="col-md-6">
                <?php echo $this->formElement($this->form->get('escalaTerca')); ?>
                <?php echo $this->formElementErrors($this->form->get('escalaTerca')); ?>  
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                Quarta-Feira 
            </div>
            
            <div class="col-md-6">
                <?php echo $this->formElement($this->form->get('escalaQuarta')); ?>
                <?php echo $this->formElementErrors($this->form->get('escalaQuarta')); ?>  
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                Quinta-Feira
            </div>
            
            <div class="col-md-6">
                <?php echo $this->formElement($this->form->get('escalaQuinta')); ?>
                <?php echo $this->formElementErrors($this->form->get('escalaQuinta')); ?>  
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                Sexta-Feira
            </div>
            
            <div class="col-md-6">
                <?php echo $this->formElement($this->form->get('escalaSexta')); ?>
                <?php echo $this->formElementErrors($this->form->get('escalaSexta')); ?>  
            </div>
        </div>
        
        

    </div>
</div>
<?= $this->form()->closeTag(); ?>