<script src="/js/inputmask.js"></script>
<script src="/js/jquery.inputmask.js"></script>

<h1>Gerar ocorrências</h1>
<form method="get" action="/sig-rh/ocorrencia/gerar">
    <div class="row">
        <div class="col-md-2">
            <label for="dataInicio">Data início:</label>
            <input type="date" title="Data de início (dd/mm/aaaa)" class="form-control" value="" name="dataInicio" id="dataInicio">
        </div>
        <div class="col-md-2">
            <label for="dataTermino">Data término:</label>
            <input type="date" title="Data de término (dd/mm/aaaa)" class="form-control" value="" name="dataTermino" id="dataTermino">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <input type="submit" class="btn btn-sm" value="Enviar">
        </div>
    </div>
</form>

<script>
    $("#periodoReferencia").inputmask("99/9999");
</script>