<?php echo $this->form()->openTag($this->form); ?>

<div class="row">
    <div class="col-md-12">
        <h3 class="panel-title">
            Por favor, preencha o formulário abaixo e, em seguida, clique sobre
            o botão <i>Salvar</i>. 
        </h3>
        <hr>
        <h4 class="panel-info">
            <?php echo (null != $this->colaborador) ? $this->escapeHtml($this->colaborador->getMatricula(). " - ". $this->colaborador->getNome(). " - Data: ".$this->dataPonto->format('d/m/Y')): " ";?>
        </h4>
        <div class="row">
            <div class="col-md-12">
                <p class="alert alert-info">
                    Escala do dia - 
                    <?php echo (null != $this->escala && null != $this->escala->getEntrada1() ? "Entrada 1: ".$this->escala->getEntrada1()->format("H:i")."hs " : "");?>
                    <?php echo (null != $this->escala && null != $this->escala->getSaida1() ? "Saída 1: ".$this->escala->getSaida1()->format("H:i")."hs " : "");?>
                    <?php echo (null != $this->escala && null != $this->escala->getEntrada2() ? "Entrada 2: ".$this->escala->getEntrada2()->format("H:i")."hs "  : "");?>
                    <?php echo (null != $this->escala && null != $this->escala->getSaida2() ? "Saída 2: ".$this->escala->getSaida2()->format("H:i")."hs "  : "");?>
                </p>
            </div>
        </div>
            
        <hr>
        <div class="row">
            <div class="col-md-12">
                <?php echo $this->formLabel($this->form->get('descricao')); ?><br>
                <?php echo $this->formElement($this->form->get('descricao')); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                <?php echo $this->formLabel($this->form->get('justificativa1')); ?><br>
                <?php echo $this->formElement($this->form->get('justificativa1')); ?>
                <?php echo $this->formElementErrors($this->form->get('justificativa1')); ?><br>                  
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                <?php echo $this->formLabel($this->form->get('justificativa2')); ?><br>
                <?php echo $this->formElement($this->form->get('justificativa2')); ?>
                <?php echo $this->formElementErrors($this->form->get('justificativa2')); ?><br>                  
            </div>
        </div>
        <div id="horarios">
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h3 class="panel-title">Ajuste os horários de entrada e saída utilizando os campos abaixo:</h3>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-3">
                    <?php echo $this->formLabel($this->form->get('entrada1')); ?><br>
                    <?php echo $this->formElement($this->form->get('entrada1')); ?>
                    <?php echo $this->formElementErrors($this->form->get('entrada1')); ?>                  
                </div>
                <div class="col-md-3">
                    <?php echo $this->formLabel($this->form->get('saida1')); ?><br>
                    <?php echo $this->formElement($this->form->get('saida1')); ?>
                    <?php echo $this->formElementErrors($this->form->get('saida1')); ?>                  
                </div>
                <div class="col-md-3">
                    <?php echo $this->formLabel($this->form->get('entrada2')); ?><br>
                    <?php echo $this->formElement($this->form->get('entrada2')); ?>
                    <?php echo $this->formElementErrors($this->form->get('entrada2')); ?>                  
                </div>
                <div class="col-md-3">
                    <?php echo $this->formLabel($this->form->get('saida2')); ?><br>
                    <?php echo $this->formElement($this->form->get('saida2')); ?>
                    <?php echo $this->formElementErrors($this->form->get('saida2')); ?>                  
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 text-right">
                    <button type="button" id="moverE1S1" class="btn btn-primary btn-sm" onclick="moverE1S1()"><span class="glyphicon glyphicon-arrow-right"> S1</span></button>
                </div>
                <div class="col-md-1 text-left">
                      <button type="button" id="moverS1E1" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-arrow-left"> E1</span></button>
                </div>
                <div class="col-md-2 text-right">
                      <button type="button" id="moverS1E2" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-arrow-right"> E2</span></button>
                </div>
                <div class="col-md-1">
                      <button type="button" id="moverE2S1" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-arrow-left"> S1</span></button>
                </div>
                <div class="col-md-2 text-right">
                      <button type="button" id="moverE2S2" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-arrow-right"> S2</span></button>
                </div>
                <div class="col-md-3">
                      <button type="button" id="moverS2E2" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-arrow-left"> E2</span></button>
                </div>
            </div>
        </div>
        <hr>
        <div id="crachaVisitante">
            <div class="row">
                <div class="col-md-5">
                    <?php echo $this->formLabel($this->form->get('numeroCrachaVisitante')); ?><br>
                    <?php echo $this->formElement($this->form->get('numeroCrachaVisitante')); ?>
                    <?php echo $this->formElementErrors($this->form->get('numeroCrachaVisitante')); ?>                  
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->formElement($this->form->get('indicarHorario')); ?>
<?php echo $this->formElement($this->form->get('indicarCracha')); ?>
<?php echo $this->form()->closeTag();

