<h1>Cadastro de feriado</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/feriado" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?php echo $this->form()->openTag($form); ?>
            
            <div class="row">
                <div class="col-md-2">
                    <?php echo $this->formLabel($form->get('dataFeriado')); ?><br>
                    <?php echo $this->formElement($form->get('dataFeriado')); ?>
                    <?php echo $this->formElementErrors($form->get('dataFeriado')); ?>                  
                </div>
                
                <div class="col-md-10">
                    <?php echo $this->formLabel($form->get('nome')); ?><br>
                    <?php echo $this->formElement($form->get('nome')); ?>
                    <?php echo $this->formElementErrors($form->get('nome')); ?>                  
                </div>
            </div>
                
            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->formLabel($form->get('descricao')); ?><br>
                    <?php echo $this->formElement($form->get('descricao')); ?>
                    <?php echo $this->formElementErrors($form->get('descricao')); ?>                  
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <?php echo $this->formLabel($form->get('tipoFeriado')); ?><br>
                    <?php echo $this->formElement($form->get('tipoFeriado')); ?>
                    <?php echo $this->formElementErrors($form->get('tipoFeriado')); ?>                  
                </div>
                
                <div class="col-md-4">
                    <?php echo $this->formLabel($form->get('expediente')); ?><br>
                    <?php echo $this->formElement($form->get('expediente')); ?>
                    <?php echo $this->formElementErrors($form->get('expediente')); ?>                  
                </div>

                
            </div>

            <div class="row">
            </div>
                
            <div class="row">
                <div class="col-sm-12 col-md-4 col-lg-3">
                    <br>
                    <div class="col-sm-12" >
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
