<?php
$form = $this->form;
$form->get('matricula')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite a matrícula aqui'
]);

$form->get('nome')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o nome aqui'
]);

$form->get('apelido')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o apelido aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de colaboradores</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/colaborador" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>

                <div class="row">
                    <div class="col-md-2"><?= $this->formRow($form->get('matricula')); ?></div>
                    <div class="col-md-8"><?= $this->formRow($form->get('nome')); ?></div>
                    <div class="col-md-2"><?= $this->formRow($form->get('apelido')); ?></div>
                </div>

                <div class="row">
                </div>
                <hr>

                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#dadosPessoais">Dados Pessoais</a></li>
                    <li><a data-toggle="tab" href="#documentacao">Documentação</a></li>
                </ul>

                <div class="tab-content">
                    <div id="dadosPessoais" class="tab-pane fade in active">
                        <p>Dados pessoais</p>
                    </div>

                    <div id="documentacao" class="tab-pane fade">
                        <p>Documentação</p>
                    </div>
                </div>

                <br>
                <br>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
