<?php
$form = $this->form;
$form->get('colaborador')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Digite o nome aqui'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-primary'
]);
?>

<h1>Cadastro de bancos</h1>

<div class="row">
    <div class="col-md-22">
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">
                    Por favor, preencha o formulário abaixo e, em seguida, clique sobre
                    o botão <i>Salvar</i>. <a
                        class="btn btn-secondary btn-sm pull-right"
                        href="/sig-rh/colaborador" title="Fechar"><span
                            class="glyphicon glyphicon-remove"></span></a>
                </h3>
            </div>

            <div class="panel-body">
                <?= $this->form()->openTag($form); ?>
                
                <?= $this->formRow ( $form->get ( 'matricula' ) ); ?>
                <?= $this->formRow ( $form->get ( 'nome' ) ); ?>
                <?= $this->formRow ( $form->get ( 'apelido' ) ); ?>
                
                <br>
                <br>
                <?= $this->formElement($form->get('submit')); ?>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
