<?php
$title = 'Excluir um registro';
$url   = $this->url('sig-rh/tipo-colaborador', ['action' => 'delete', 'id' => $tipoColaborador->getId()]);
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Deseja realmente excluir 
    "<?= $this->escapeHtml($tipoColaborador->getDescricao()); ?>"
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $tipoColaborador->getId() ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-success" name="del" value="Não" />
    </div>
</form>