<?php

return [
    'acl' => array(
		'roles' => array(
                        'convidado' => null,
                        'secretaria' => 'convidado',
			'comum' => 'secretaria',
			'admin' => 'comum',
		),
		'resources' => array(
                        'Application\Controller\Index.index',
                        'Rastrea\Controller\Fase.index',
                        'Rastrea\Controller\Fase.save',
                        'Rastrea\Controller\Fase.delete',
                        'Rastrea\Controller\Fase.busca',
                        'Rastrea\Controller\Material.index',
                        'Rastrea\Controller\Material.save',
                        'Rastrea\Controller\Material.delete',
                        'Rastrea\Controller\Material.busca',
                        'Rastrea\Controller\Material.importar',
                        'Rastrea\Controller\Material.ajax-list',
                        'Rastrea\Controller\Material.ajax-list2',

                        'Rastrea\Controller\Movto.index',
                        'Rastrea\Controller\Movto.save',
                        'Rastrea\Controller\Movto.delete',
                        'Rastrea\Controller\Movto.busca',
                    
                        'Rastrea\Controller\Lote.index',
                        'Rastrea\Controller\Lote.save',
                        'Rastrea\Controller\Lote.delete',
                        'Rastrea\Controller\Lote.busca',
                        'Embraorc\Controller\Recurso.index',
                        'Embraorc\Controller\Recurso.save',
                        'Embraorc\Controller\Recurso.delete',
                        'Embraorc\Controller\Recurso.busca',
                        'Rastrea\Controller\Movimentacao.index',
                        'Rastrea\Controller\Movimentacao.extrato',
                        'Rastrea\Controller\Movimentacao.save',
                        'Rastrea\Controller\Movimentacao.delete',
                        'Rastrea\Controller\Movimentacao.busca',
                        'Rastrea\Controller\Movimentacao.apaga-mov',
                        'Rastrea\Controller\Movimentacao.seleciona-atividade',
                        'Rastrea\Controller\Movimentacao.sucesso',
                        'Rastrea\Controller\Movimentacao.importar',
                        'Embraorc\Controller\Relmovimentacao.index',
                        'Embraorc\Controller\Relmovimentacao.gerar-html',
                        'Embraorc\Controller\Relacumulado.index',
                        'Embraorc\Controller\Relacumulado.gerar-html',
                        'Embraorc\Controller\Relatividadevigente.index',
                        'Embraorc\Controller\Relatividadevigente.gerar-html',
                        'Rastrea\Controller\Relextrato.index',
                        'Rastrea\Controller\Relextrato.gerar-html',
                        'Rastrea\Controller\Relestoque.index',
                        'Rastrea\Controller\Relestoque.gerar-html',
                        'Rastrea\Controller\Sobre.index',
                        'Fontes\Controller\Parceiro.index',
                        'Fontes\Controller\Parceiro.save',
                        'Fontes\Controller\Parceiro.delete',
                        'Fontes\Controller\Parceiro.busca',
                        'Fontes\Controller\Fontes.save-equipe',
                        'Fontes\Controller\Fontes.delete-equipe',
                        'Fontes\Controller\Relfontes.index',
                        'Fontes\Controller\Relfontes.gerar-html',
			'Admin\Controller\Index.save',
			'Admin\Controller\Index.delete',
			'Admin\Controller\Auth.index',
			'Admin\Controller\Auth.login',
			'Admin\Controller\Auth.logout',
			'Admin\Controller\Usuario.index',
			'Admin\Controller\Usuario.save',
			'Admin\Controller\Usuario.busca',
			'Admin\Controller\Usuario.delete',
			),
		'privilege' => array(
                        'convidado' => array(
				'allow' => array(
                                    'Application\Controller\Index.index',
                                    'Admin\Controller\Auth.index',
                                    'Admin\Controller\Auth.login',
                                    'Admin\Controller\Auth.logout',
                                    )
                            ),
			'comum' => array(
				'allow' => array(
                                        
                                        'Rastrea\Controller\Fase.index',
                                        'Rastrea\Controller\Fase.save',
                                        'Rastrea\Controller\Fase.delete',
                                        'Rastrea\Controller\Fase.busca',
                                        'Rastrea\Controller\Material.index',
                                        'Rastrea\Controller\Material.save',
                                        'Rastrea\Controller\Material.delete',
                                        'Rastrea\Controller\Material.busca',
                                        'Rastrea\Controller\Material.importar',
                                        'Rastrea\Controller\Material.ajax-list',
                                        'Rastrea\Controller\Material.ajax-list2',
                                        'Rastrea\Controller\Movto.index',
                                        'Rastrea\Controller\Movto.save',
                                        'Rastrea\Controller\Movto.delete',
                                        'Rastrea\Controller\Movto.busca',
                                        'Rastrea\Controller\Lote.index',
                                        'Rastrea\Controller\Lote.save',
                                        'Rastrea\Controller\Lote.delete',
                                        'Rastrea\Controller\Lote.busca',
                                        'Embraorc\Controller\Recurso.index',
                                        'Embraorc\Controller\Recurso.save',
                                        'Embraorc\Controller\Recurso.delete',
                                        'Embraorc\Controller\Recurso.busca',
                                        'Rastrea\Controller\Movimentacao.index',
                                        'Rastrea\Controller\Movimentacao.extrato',
                                        'Rastrea\Controller\Movimentacao.save',
                                        'Rastrea\Controller\Movimentacao.delete',
                                        'Rastrea\Controller\Movimentacao.apaga-mov',
                                        'Rastrea\Controller\Movimentacao.busca',
                                        'Rastrea\Controller\Movimentacao.seleciona-atividade',
                                        'Rastrea\Controller\Movimentacao.sucesso',
                                        'Rastrea\Controller\Movimentacao.importar',
                                        'Embraorc\Controller\Relacumulado.index',
                                        'Embraorc\Controller\Relacumulado.gerar-html',
                                        'Embraorc\Controller\Relatividadevigente.index',
                                        'Embraorc\Controller\Relatividadevigente.gerar-html',
                                        'Rastrea\Controller\Relextrato.index',
                                        'Rastrea\Controller\Relextrato.gerar-html',
                                        'Rastrea\Controller\Relestoque.index',
                                        'Rastrea\Controller\Relestoque.gerar-html',
                                        'Rastrea\Controller\Sobre.index',
                                        'Fontes\Controller\Relfontes.index',
                                        'Fontes\Controller\Relfontes.gerar-html',
                                        'Fontes\Controller\Parceiro.index',
                                        'Fontes\Controller\Parceiro.save',
                                        'Fontes\Controller\Parceiro.delete',
                                        'Fontes\Controller\Parceiro.busca',
                                        
				)
			),
			'admin' => array(
				'allow' => array(
                                        'Admin\Controller\Index.delete',
					'Admin\Controller\Usuario.index',
                 			'Admin\Controller\Usuario.busca',
					'Admin\Controller\Usuario.save',
					'Admin\Controller\Usuario.delete',
                                        'Embraorc\Controller\Relmovimentacao.index',
                                        'Embraorc\Controller\Relmovimentacao.gerar-html',
				)
			),
			'secretaria' => array(
				'allow' => array(
                                        'Embraorc\Controller\Relatividadevigente.index',
                                        'Embraorc\Controller\Relatividadevigente.gerar-html',
				)
			),
                    
		)
	)
    
];
